### ISSUE TITLE
Insert problems from dqlite shell

### ISSUE THREAD

**Issue by geosoft1** [canonical/go-dqlite#107]
Trying to do some inserts into a dqlite database from dqlite shell I observed that the insert statement seems to overwrite records, eg:

```
dqlite> CREATE TABLE test (id INT, s TEXT)
dqlite> INSERT INTO test VALUES (1, 'a')
dqlite> INSERT INTO test VALUES (2, 'b')
dqlite> SELECT * FROM test
2|b
dqlite> 
```

**Comment by freeekanayaka** [comment]
I couldn't reproduce this, at least with the demo application:

```bash
$ dqlite-demo -a 127.0.0.1:8001 -d 127.0.0.1:9001 &
[1] 99711
$ dqlite-demo -a 127.0.0.1:8002 -d 127.0.0.1:9002 -j 127.0.0.1:9001 &
[2] 99727
$ dqlite-demo -a 127.0.0.1:8003 -d 127.0.0.1:9003 -j 127.0.0.1:9001 &
[3] 99739
$ dqlite -s 127.0.0.1:9001,127.0.0.1:9002,127.0.0.1:9003 test
dqlite> CREATE TABLE test (id INT, s TEXT)
dqlite> INSERT INTO test VALUES (1, 'a')
dqlite> INSERT INTO test VALUES (2, 'b')
dqlite> SELECT * FROM test;
1|a
2|b
```

Do you have a more detailed list of steps to follow?

**Comment by geosoft1** [comment]
![Screenshot from 2020-06-08 17-06-50](https://user-images.githubusercontent.com/6298396/84041259-45e00600-a9ac-11ea-9eba-bcc291859955.png) 
Well, I ran exactly the test with default demo application and I obtained the same result. Dqlite is installed on Ubuntu 18.04 with:
```
sudo add-apt-repository -y ppa:dqlite/stable
sudo apt-get install dqlite libdqlite-dev
```
But I don't have this problem from my applications, where I'm able to send insert commands through sqlite driver to dqlite that works well.

**Comment by freeekanayaka** [comment]
The `dqlite` shell is currently not included in the deb package in the stable archive, so I assume you have built the binary yourself with something `go install -tags libsqlite3 ./cmd/dqlite`.

Assuming that's the case, your clone of the `go-dqlite` git repo is probably behind master, since the bug you are seeing was fixed a few days ago by https://github.com/canonical/go-dqlite/pull/104/commits/f90c4bc95c09fb301f8b5c81fb1f8515c37dad8a .

Please try to run `go get -tags libsqlite3 -u github.com/canonical/go-dqlite`, then rebuild the shell binary. That should fix the issue.

**Comment by geosoft1** [comment]
I've done this and indeed solved the problem. Thank you for your help and for the quick answer.
