### ISSUE TITLE
Is it possible to let it work with hostnames instead of ip addresses?

### ISSUE THREAD

**Issue by mogui** [canonical/go-dqlite#133]
I'm trying to use dqlite for an application that will live as a container inside Kubernetes as a StatefulSet.
The problem is that Kubernetes for his nature don't assign fixed ips to containers, so when an app using dqlite get restarted its ip changes, breaking how dqlite try to reconfigure the cluster having that logic based on ips.

It is something that could be possible to change? 
which part has to be modified to let this happen? 

I investigated just bit the code and could we write in store files (cluster.yaml, info.yaml) hostnames and then resolve to ips at runtime?

If someone  could direct me to the right points, I can make a pull request by my own.

Thanks

**Comment by freeekanayaka** [comment]
If you use the TLS proxy code (e.g. via it's [helper](https://pkg.go.dev/github.com/canonical/go-dqlite@v1.8.0/app#SimpleTLSConfig) in the `app` package, which btw is the recommended way to consume go-dqlite these days, see the demo code), then yes you should be able to use hostnames because those will be resolved as part of the TLS connection.

If you don't use TLS though, then no DNS resolution will take place because the connection will be established directly using the low-level C code and that doesn't yet know how to handle hostnames (that alone would probably be a nice feature to add, although most people really should just go for TLS for real-world applications).

**Comment by freeekanayaka** [comment]
You can also look at the unit tests in the `app` package to see a full TLS-based dqlite setup that uses the `app` helpers.

**Comment by mogui** [comment]
great! I'll try to go with the TLS-based
many thanks
