### ISSUE TITLE
Unable to execute demo, Invalid flag error

### ISSUE THREAD

**Issue by joseims** [canonical/go-dqlite#149]
I'm trying to execute the demo, but when i get to the command:
```go install -tags libsqlite3 ./cmd/dqlite-demo```

I got the following error

```go build github.com/canonical/go-dqlite/internal/bindings: invalid flag in #cgo LDFLAGS: -Wl,-z,now```

After i ran:

```export CGO_LDFLAGS_ALLOW="-Wl,-z,now"```

The errors now is:

```internal/bindings/server.go:166:11: could not determine kind of name for C.dqlite_node_set_snapshot_params```

for both ```go build -tags libsqlite3``` and  ```go install -tags libsqlite3 ./cmd/dqlite-demo```

I'm using a fresh install of ```go version go1.15.13 linux/amd64``` on ubuntu 20.04.

I'm also very unexperient with go, so it can also so be some simple thing i'm missing

**Comment by MathieuBordere** [comment]
You need a more recent version of dqlite to fix that error, if the version in the ppa is outdated, you can build it from source, see `Build` section in the README [here](https://github.com/canonical/dqlite)

**Comment by joseims** [comment]
I builded it following the guide and still have the same error

**Comment by joseims** [comment]
I made it work by excluding `-Wl,-z,now` from `/internal/bindings/build.go`

**Comment by MathieuBordere** [comment]
Excluding them is not a huge risk, they have only been introduced recently. The flags force symbol resolution when the binary is loaded instead of lazy symbol resolution when the program is about to call a function of a dynamic library. Resolving the symbols at load time has the advantage that your program will not 'crash' if it can't find a symbol at runtime.

The build should normally work, I'll close this one for now, and add a Makefile so the build experience is smoother.
