### ISSUE TITLE
dqlite does not report any leader

### ISSUE THREAD

**Issue by jeromer** [canonical/go-dqlite#203]
Hi there,

I'm giving dqlite a try, and I just applied the following commands with the demo program:

```
dqlite-demo -v --api 127.0.0.1:8001 --db 127.0.0.1:9001
dqlite-demo -v --api 127.0.0.1:8002 --db 127.0.0.1:9002 --join 127.0.0.1:9001
dqlite-demo -v --api 127.0.0.1:8003 --db 127.0.0.1:9003 --join 127.0.0.1:9001
```

According to the logs, there is an elected leader:

```
[...]
2022/09/08 21:56:38 127.0.0.1:8003: DEBUG: attempt 1: server 127.0.0.1:9001: connect to reported leader 127.0.0.1:9002
2022/09/08 21:56:38 127.0.0.1:8003: DEBUG: attempt 1: server 127.0.0.1:9001: connected
[...]
```

However, when I run `.cluster` from the `dqlite` command, like this `dqlite -s 127.0.0.1:9001 /tmp/dqlite-demo/127.0.0.1:9002`, I get the following output:
```
dqlite -s 127.0.0.1:9001 /tmp/dqlite-demo/127.0.0.1:9001
dqlite> .cluster
2dc171858c3155be|127.0.0.1:9001|voter
7f60f4c8d1fb81f2|127.0.0.1:9002|voter
588d2ca432a7bb09|127.0.0.1:9003|voter
dqlite> %                            
```

`7f60f4c8d1fb81f2|` is not reported as leader contrary to what I see from the logs.

All of this was noticed after fresh `git clone` from the `master` branch.

Did I do anything wrong ?

Thanks :)

**Comment by jeromer** [comment]
And also:
```
$ curl -X PUT -d my-value http://127.0.0.1:8001/my-key  
done

$ curl http://127.0.0.1:8001/my-key 
my-value

$ dqlite -s 127.0.0.1:9001 /tmp/dqlite-demo/127.0.0.1:9001
dqlite> select * from model;
Error:  query: no such table: model
```
Maybe I simply use the `dqlite` CLI the wrong way ?

**Comment by MathieuBordere** [comment]
Hi,

the `.leader` command should show you who the current leader is.
`.cluster` only shows the configuration of the cluster, the nodes with their `id`, `address` and `role`.

To query the database you have to use the command like this `dqlite -s 127.0.0.1:9001 demo`, the second argument is the name of the database. For dqlite-demo, it is set [here](https://github.com/canonical/go-dqlite/blob/bc17ff15806fbd36f9eb481e0d9e80fe057d3b33/cmd/dqlite-demo/dqlite-demo.go#L55).

We'll extend the docs / README, because it's indeed not very clear atm. I also noticed that the cli prints the bytes values of the strings when you do something like.
```
$ curl -X PUT -d my-value http://127.0.0.1:8001/my-key  
done

dqlite -s 127.0.0.1:9001 demo
dqlite> select * from model;
my-key|[109 121 45 118 97 108 117 101]
```
I'll take a look at that too.
