### ISSUE TITLE
dqlite CLI hangs when executed against a stand-by node

### ISSUE THREAD

**Issue by jeromer** [canonical/go-dqlite#216]
Hi there,

When I run the following command against a `voter` node, everything works fine:
```
   dqlite -s 1.2.3.4.5:9001 mydb .leader
```

(It works fine when I call `.cluster` too)

However, when I run the exact same command on a stand-by node (as reported by `.cluster`) the CLI simply hangs.

It that an expected behaviour ?

On a side note, is is possible to get more than 3 `voter` nodes ? Will a `stand-by` nodes still replicate data as a `voter` node ? 

Thanks :)

**Comment by jeromer** [comment]
Hi Cole, thanks for the quick reply. If it helps I just reproduced the problem on a fresh `git pulled` go-dqlite repo (`master` branch).
Here is the test case (I use one tmux pane per command):
```dqlite-demo --api 127.0.0.1:8001 --db 127.0.0.1:9001 --verbose
dqlite-demo --api 127.0.0.1:8002 --db 127.0.0.1:9002 --join 127.0.0.1:9001 --verbose
dqlite-demo --api 127.0.0.1:8003 --db 127.0.0.1:9003 --join 127.0.0.1:9001 --verbose
dqlite-demo --api 127.0.0.1:8004 --db 127.0.0.1:9004 --join 127.0.0.1:9001 --verbose
dqlite-demo --api 127.0.0.1:8005 --db 127.0.0.1:9005 --join 127.0.0.1:9001 --verbose
dqlite-demo --api 127.0.0.1:8006 --db 127.0.0.1:9006 --join 127.0.0.1:9001 --verbose
```
And in a different window/tab:
```watch timeout 1 dqlite -s 127.0.0.1:9001 demo .cluster```

You should see something which looks like this:
```2dc171858c3155be|127.0.0.1:9001|voter
400635726eb0a062|127.0.0.1:9002|voter
8e1ef6864fad142c|127.0.0.1:9003|voter
aa7b0f7e83b5861c|127.0.0.1:9004|stand-by
501587e42e89570f|127.0.0.1:9005|stand-by
e8d3862208745871|127.0.0.1:9006|stand-by
```
For some reason I sometimes happened to see 4 voters and 2 stand-by nodes instead of an 3 voters and 4 stand-by nodes but this happened seldom.

> Yes and yes: you can have an arbitrary (odd) number of voters, 

I believe this is some kind of configuration switch/variable when initializing a new dqlite app ?

> standby nodes replicate log entries just like voters do -- the only difference is that standby nodes don't participate in elections and can't become candidates or leaders.

Perfect, I suspected something like this, but I prefered asking.

Thanks :)

**Comment by jeromer** [comment]
Awesome, thanks :)

**Comment by MathieuBordere** [comment]
The problem is that the shell only asks the nodes supplied in the server list `-s` who the leader is, the only server in that list is a stand-by node and because the node is stand-by, it doesn't know the answer and the code tries asking the next node, in this case, the same node and the loop continues forever, because there is no timeout on the context.

I'm not immediately inclined to change the behavior as perhaps some people depend on the function retrying forever. We could perhaps add a user-supplied timeout to the commands.

So it's a matter of supplying the whole cluster info to the command like this
`dqlite -s file:///tmp/dqlite-demo/127.0.0.1\:9004/cluster.yaml mydb .leader`
