### ISSUE TITLE
Issues with sharing a connection between statements (?)

### ISSUE THREAD

**Issue by cole-miller** [canonical/go-dqlite#257]
Is it a problem that right now multiple `Stmt` objects share a dqlite server connection with each other and with the `DB` object (`DB.ExecContext()`, etc.)? It seems like this kind of situation could occur:

- We `Query` Stmt A
- Concurrently, we `Query` Stmt B that's open on the same DB
- When the dqlite server sends rows in response, it's not clear to which Stmt they pertain

**Comment by freeekanayaka** [comment]
> Is it a problem that right now multiple `Stmt` objects share a dqlite server connection with each other and with the `DB` object (`DB.ExecContext()`, etc.)? It seems like this kind of situation could occur:
> 
> * We `Query` Stmt A
> * Concurrently, we `Query` Stmt B that's open on the same DB
> * When the dqlite server sends rows in response, it's not clear to which Stmt they pertain

This should all be taken care by the `sql` Go package. What `go-dqlite` implements is the driver interface (which the `sql` package uses).

**Comment by freeekanayaka** [comment]
> Fwiw, when developing the C client I gave each dqlite_stmt object its own connection to avoid this kind of issue. But maybe go-dqlite (or database/sql) is doing something that causes it not to be an issue?

FWIW the way SQLite itself solves this is basically by using locks (see https://www.sqlite.org/threadsafe.html), so it supports using the same connection in multiple threads.

As far as dqlite is concerned the only rule the client needs to observe (regardless of the language) is that for every request that the client sends the client must wait for the response before sending another request (there are just a couple exceptions I think, like interrupts and heartbeats, which are not quite used at the moment IIRC).

Since we send query responses in batches, it's possible to use a single connection to multiplex several queries/statements without much performance/latency penalty.

**Comment by freeekanayaka** [comment]
> Is it a problem that right now multiple `Stmt` objects share a dqlite server connection with each other and with the `DB` object (`DB.ExecContext()`, etc.)? It seems like this kind of situation could occur:
> 
> * We `Query` Stmt A
> * Concurrently, we `Query` Stmt B that's open on the same DB
> * When the dqlite server sends rows in response, it's not clear to which Stmt they pertain

In case of Go this does not happen, because a different connection would be used (there's a connection pool). In the of the C client, perhaps a connection pool could be used too (to avoid opening too many connections), although that's an optimization that could be put in place when and if the current approach becomes an issue.
