### ISSUE TITLE
Understanding problem consistency, scalability and leader 

### ISSUE THREAD

**Issue by koh-osug** [canonical/go-dqlite#283]
* When a write happens is this write handled on the elected leader only or must there by a quorum? 
* I had the impression there is only one leader dynamically elected handling all writes from all other nodes, is this wrong?
* If there is a quorum necessary, then this quorum is automatically decreased if nodes are failing or leaving the cluster?
* What are the scaling limits? Are 100 nodes still OK?
* Can read be executed locally? I see in the documentation: "When a client performs a read transaction (e.g. a transaction that involves only SELECT statements) the server merely maps client". This seems to indicate that the leader is udner heavy traffic from all clients in the system?

**Comment by cole-miller** [comment]
> When a write happens is this write handled on the elected leader only or must there by a quorum?

Writes are replicated to a quorum (outright majority) of voting nodes before being committed on the leader.

> I had the impression there is only one leader dynamically elected handling all writes from all other nodes, is this wrong?

That's correct.

> If there is a quorum necessary, then this quorum is automatically decreased if nodes are failing or leaving the cluster?

The quorum is based on the current cluster configuration, which a a list of nodes, each assigned one of three roles: voter, standby, spare. A majority of voters is required for the quorum. The configuration can change dynamically (such changes go through more or less the same replication and commit process as normal writes). If you use the high-level `App` wrapper of go-dqlite, nodes that join the cluster will be automatically assigned an appropriate role, and these assignments will be automatically adjusted when a node stops responding. The assignment is based on target numbers of voters and standbys that you configure on the `App`.

> What are the scaling limits? Are 100 nodes still OK?

That should be fine, the relevant scaling limits for dqlite currently are more to do with the size of the data set.

> Can read be executed locally? I see in the documentation: "When a client performs a read transaction (e.g. a transaction that involves only SELECT statements) the server merely maps client". This seems to indicate that the leader is udner heavy traffic from all clients in the system?

Reads are forwarded to the leader rather than being executed locally, yes. The motivation for this is that we want to execute a Raft "barrier" in some cases before servicing a read, and only the leader can execute barriers. Allowing reads to be serviced locally is something we'd like to work on in the future, though.

**Comment by koh-osug** [comment]
Thank you.

**Comment by koh-osug** [comment]
When digging into the Raft consensus algorithm I always see a limit of 9-11 nodes as a limit, otherwise the processing time becomes unwieldy as others say. Since dqlite is using Raft I'm wondering if really a 100 node setup is still fine, i.e. this would still require a quorum also of 51 nodes in dqlite, right?

**Comment by freeekanayaka** [comment]
> When digging into the Raft consensus algorithm I always see a limit of 9-11 nodes as a limit, otherwise the processing time becomes unwieldy as others say. Since dqlite is using Raft I'm wondering if really a 100 node setup is still fine, i.e. this would still require a quorum also of 51 nodes in dqlite, right?

No, by default a cluster of 100 dqlite nodes will have 3 voters, with a quorum of 2 nodes. Dqlite will automatically assign or de-assign the voter role to nodes if it notices that they become available or un-available.

See also:

https://pkg.go.dev/github.com/canonical/go-dqlite@v1.21.0/app#WithVoters

and

https://pkg.go.dev/github.com/canonical/go-dqlite@v1.21.0/app#WithStandBys

(stand-bys are "hot" nodes that receive data updates but don't count for quorum, they can be turned into voters quickly if need, e.g. when dqlite notices that a voter has gone offline).
