### ISSUE TITLE
Listener for database updates

### ISSUE THREAD

**Issue by koh-osug** [canonical/go-dqlite#284]
Is it possible to be informed about database update, i.e. data updates, data creation, data deletion by some listener? I'm looking for a hook for getting informed about delta updates to trigger some business logic.

**Comment by cole-miller** [comment]
Not currently, you'd need to manually poll for the changes you're interested in using normal SQL queries. This is another feature that we would like to add in the future, but it's waiting on an ongoing revamp of how dqlite stores its data.

**Comment by koh-osug** [comment]
OK, thanks.

**Comment by gl-yziquel** [comment]
This is a feature I'd pretty much need. I'm running some "old" code based on OPS5 algorithms for matching on patterns in memory (OPS5 -> Rete algorithm, that is implemented in Drools nowadays), and I'd love if part of that memory on which this pattern is done could mirror the state of the dqlite db.

I'm not looking for a perfect solution. But if I could hack out something w/r to dqlite backend to have that backend dumped into the memory of my application instead of a regular DB, I'd be more happy.

Pointers to places in the code that could or should be hacked would be welcome.
