### ISSUE TITLE
Expose GO_DQLITE_MULTITHREAD programmatically

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/go-dqlite#54]
Right now setting GO_DQLITE_MULTITHREAD=1 is required in my application because I use sqlite in tandem with dqlite and my sqlite instance is expected to be multithreaded.  Its not feasible to have all users set GO_DQLITE_MULTITHREAD=1 env var and it's a bit fragile if I do os.Setenv in an init() method because it may run before or after go-dqlite.init().

Ideally it would be nice if singlethread mode was just not set by default, but if that is not feasible then is it possible to expose a method to set Multithread mode that can be called from a consumers init method?

**Comment by freeekanayaka** [comment]
For now I decided to keep the current behavior of enabling Single-thread mode by default, since it's what most people consuming dqlite should use.

However the new [```ConfigMultiThread```](https://godoc.org/github.com/canonical/go-dqlite#ConfigMultiThread) API should be enough to let you safely change that, but see the caveats in the docstring.
